name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Frozen Desserts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: Run test
      run: bundle exec rspec spec